### ISSUE TITLE
Actividad 2 ejercicios equipo JP 

### ISSUE THREAD

**Issue by Juan27231** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-de-jp#1]
[Actividad 2 ejercicios equipo JP .pdf](https://github.com/user-attachments/files/16839975/Actividad.2.ejercicios.equipo.JP.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado 
Portada: 25/25
Procedimiento: 25/25
Figuras, ilustraciones y fotografías: 25/25
Resultados y conclusiones: 25/25
Calificación: 20 /20
